services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    volumes:
      - /srv/homelab/.cloudflared:/etc/cloudflared:ro
    restart: unless-stopped
    networks:
      - edge

networks:
  edge:
    external: true
